import { Badge, EmptyState, LoadingState, PageHeading, Panel, ResourceNotice } from '../components/Common'
import { Icon } from '../components/Icon'
import type { IconName } from '../components/Icon'
import { count, eventLabels, formatDate, newestFirst } from '../utils/format'
import type { PageProps } from './types'
export function Dashboard({ state, refresh, refreshButton }: PageProps) {
  const overview = state.data?.overview
  const recent = newestFirst(state.data?.events ?? [], event => event.timestamp).slice(0, 5)
  const stats: { label: string; value?: number | null; icon: IconName; tone: string; hint: string }[] = [
    { label: 'Thiết bị đã phát hiện', value: overview?.totalDevices, icon: 'usb', tone: 'blue', hint: 'Tất cả thiết bị USB' },
    { label: 'USB bị chặn', value: overview?.blockedDevices, icon: 'block', tone: 'red', hint: 'Thiết bị bị từ chối truy cập' },
    { label: 'USB được phép', value: overview?.allowedDevices, icon: 'check', tone: 'green', hint: 'Thiết bị trong whitelist' },
    { label: 'Sự kiện gần đây', value: overview?.recentEvents, icon: 'history', tone: 'purple', hint: 'Theo thống kê từ máy chủ' },
  ]
  return <><PageHeading eyebrow="SECURITY OVERVIEW" title="Tổng quan bảo vệ" description="Theo dõi thiết bị, kiểm soát kết nối và bảo vệ hệ thống của bạn.">{refreshButton}</PageHeading><ResourceNotice state={state} retry={refresh} />
    <section className="protection-banner"><div className="protection-visual"><Icon name="shield" size={50} /><span className="orbit orbit-one" /><span className="orbit orbit-two" /></div><div className="protection-copy"><div className="eyebrow">USB PROTECTION</div><h2>{overview?.protection === 'enabled' ? 'Hệ thống đang được bảo vệ' : overview?.protection === 'disabled' ? 'USB Protection đã tắt' : 'Sẵn sàng cho một hệ thống an toàn hơn'}</h2><p>{overview?.protection === 'enabled' ? 'Theo dõi thiết bị và chính sách bảo vệ tại một nơi.' : overview?.protection === 'disabled' ? 'Dịch vụ chưa bật bảo vệ. Kiểm tra cấu hình hệ thống.' : 'Kết nối dịch vụ để theo dõi và kiểm soát các thiết bị USB.'}</p><div className="protection-badges"><Badge tone={overview?.protection === 'enabled' ? 'green' : overview?.protection === 'disabled' ? 'red' : 'neutral'}>{overview?.protection === 'enabled' ? 'Đang bảo vệ' : overview?.protection === 'disabled' ? 'Đã tắt' : 'Chưa xác định trạng thái'}</Badge><span className="service-caption"><span className="status-dot" />Service: {overview?.service === 'running' ? 'Đang chạy' : overview?.service === 'stopped' ? 'Đã dừng' : 'Chưa xác định'}</span></div></div><a href="#/settings" className="button banner-button">Cấu hình hệ thống <Icon name="arrow" size={16} /></a></section>
    <div className="stats-grid">{stats.map(stat => <section className="stat-card" key={stat.label}><div className="stat-top"><span>{stat.label}</span><span className={`stat-icon ${stat.tone}`}><Icon name={stat.icon} /></span></div><div className="stat-value">{state.status === 'loading' ? <span className="stat-skeleton skeleton" /> : count(stat.value)}</div><p>{stat.hint}</p></section>)}</div>
    <div className="dashboard-columns"><Panel title="Hoạt động USB gần nhất" subtitle="Các kết nối và thay đổi chính sách mới nhất" action={<a className="panel-link" href="#/events">Xem tất cả <Icon name="arrow" size={15} /></a>}>{state.status === 'loading' ? <LoadingState /> : recent.length ? <div className="activity-list">{recent.map(event => <div className="activity" key={event.id}><span className={`stat-icon ${event.type === 'blocked' ? 'red' : 'green'}`}><Icon name={event.type === 'blocked' ? 'block' : 'usb'} /></span><div><strong>{event.message}</strong><p>{event.deviceName ?? 'Thiết bị chưa xác định'} · {event.endpointName ?? 'Chưa rõ endpoint'}</p><Badge>{eventLabels[event.type]}</Badge></div><time dateTime={event.timestamp}>{formatDate(event.timestamp)}</time></div>)}</div> : <EmptyState icon="history" title={state.status === 'ready' ? 'Chưa có hoạt động USB' : 'Chưa nhận được hoạt động USB'} description={state.status === 'ready' ? 'Các hoạt động cắm, tháo và thay đổi quyền USB sẽ xuất hiện tại đây.' : 'Lịch sử hoạt động sẽ xuất hiện khi dịch vụ cung cấp dữ liệu.'} />}<div className="panel-bottom"><Icon name="clock" size={15} /><span>Sắp xếp theo thời gian mới nhất</span></div></Panel>
    <Panel title="Trạng thái endpoints" subtitle="Các máy tính trong hệ thống" action={<Icon name="monitor" />}><div className="endpoint-summary"><div className="status-ring"><Icon name="monitor" size={28} /><strong>{overview?.onlineEndpoints != null && overview.offlineEndpoints != null ? count(overview.onlineEndpoints + overview.offlineEndpoints) : '—'}</strong><span>ENDPOINTS</span></div><div className="endpoint-legend"><div><span><i className="legend-dot green-dot" />Online</span><strong>{count(overview?.onlineEndpoints)}</strong></div><div><span><i className="legend-dot" />Offline</span><strong>{count(overview?.offlineEndpoints)}</strong></div></div></div><a className="panel-bottom panel-bottom-link" href="#/endpoints">Quản lý endpoints <Icon name="arrow" size={16} /></a></Panel></div>
    <div className="dashboard-columns lower-columns"><Panel title="Truy cập nhanh" subtitle="Quản lý chính sách bảo vệ"><div className="quick-links"><a href="#/devices"><span className="stat-icon blue"><Icon name="usb" /></span><div><strong>Thiết bị USB</strong><p>Tra cứu các thiết bị đã phát hiện</p></div><Icon name="arrow" size={18} /></a><a href="#/whitelist"><span className="stat-icon green"><Icon name="check" /></span><div><strong>Whitelist & Policy</strong><p>Kiểm soát thiết bị được phép sử dụng</p></div><Icon name="arrow" size={18} /></a></div></Panel><Panel title="Người dùng gần đây" subtitle="Theo các sự kiện từ endpoints">{recent.some(event => event.username) ? <ul className="recent-users">{[...new Set(recent.map(event => event.username).filter(Boolean))].map(user => <li key={user}><Icon name="user" />{user}</li>)}</ul> : <div className="compact-empty"><Icon name="user" size={22} /><p>Chưa có dữ liệu người dùng từ hệ thống.</p></div>}</Panel></div>
  </>
}
